### PR TITLE
Add @rodion-arr to members

### PR DESCRIPTION
**Pull request by rodion-arr**
Hi,

I'd like to join community and ready to invest time in developing Node.js ecosystem.
Will be glad to reinforce your team and help with packages' issues\requests.

### CODE REVIEW

**Comment by ghinks** [comment]
Just turn up to the next meeting , we are very welcoming.

**Comment by ghinks** [comment]
https://github.com/nodejs/package-maintenance/issues/379

**Comment by thescientist13** [comment]
Welcome @rodion-arr !  👋

**Comment by rodion-arr** [comment]
Thank you all!

**Pull request merged**
