### PR TITLE
tools.md: add bevry's automation tooling

### LINKED ISSUE #5: Tooling to assist maintenance
Travis CI recently informed me that I have over 800 packages using it.

I've done up the following tooling to assist in automating the maintenance of my packages as much as possible, they have been used for years, and probably others will find them useful:

- https://github.com/bevry/badges
- https://github.com/bevry/projectz
- https://github.com/bevry/boundation
- https://github.com/bevry/awesome-travis

### PR DESCRIPTION
**Pull request by balupton**
close #5

/cc #114 #172 #280 #298 #299

### CODE REVIEW

**Comment by balupton** [comment]
In hindsight, I think `tools.md` should just be replaced by say a `awesome-maintenance` repo that follows in the awesome-* spirit.

**Comment by ljharb** [comment]
why is this a standard we’re endorsing? I don’t think it’s appropriate for a node group to bless a particular community convention, even for an informational list.

**Comment by wesleytodd** [comment]
TBQH, I think we should just delete this file until we have some clear purpose for it.  I suspect we will never want it as it would give too much weight even on the tools we end up building and supporting.

**Comment by mhdawson** [comment]
I agree we should just delete the file.

**Comment by mhdawson** [comment]
Going close this out since we are going to remove the file anyway.

**Pull request closed without merging**
