### PR TITLE
I would like to participate in the project

### PR DESCRIPTION
**Pull request by seta-minhnguyen**
I can help to upgrade packages dependencies, especially those involve security issues.

### CODE REVIEW

**Comment by Eomm** [comment]
LGTM Welcome! 💪

**Comment by Eomm** [comment]
@seta-minhnguyen, is correct adding the account `@truongminh` and not yours `seta-minhnguyen`?

**Comment by truongminh** [comment]
Please add my personal account truongminh.
Thank @Eomm

**Comment by wentout** [comment]
@Eomm, now acc @seta-minhnguyen received contribution status, and @truongminh did not.
Cause of how that PR was made and then shipped. @truongminh seems you have to make one else PR from yours personal acc if you wish this to be finished properly.

**Comment by Eomm** [comment]
Oh sorry, you are right: I will remember to alert that information if will happen again this kind of PR

**Pull request merged**
