### PR TITLE
fix: removed tools.md

### PR DESCRIPTION
**Pull request by wesleytodd**
As discussed in https://github.com/nodejs/package-maintenance/pull/300

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
should we close down #347 and remove this from [the ToC](https://github.com/nodejs/package-maintenance/tree/master/docs#table-of-contents) as well?

**Comment by wesleytodd** [comment]
Removed the TOC reference, want to close that one since it is your issue?

**Review by dominykas — APPROVED** [review]

**Review by thescientist13 — APPROVED** [review]

**Comment by thescientist13** [comment]
closed #347 and marked as **invalid**

**Review by rodion-arr — APPROVED** [review]

**Review by Eomm — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
