### PR TITLE
Add @nairihar

### PR DESCRIPTION
**Pull request by nairihar**
Hi everyone, I'm a big fan of JavaScript/Node.js and related technologies.
I would like to become a contributor to that technologies and communicate with others.
 and take/share new skills. It's a very good opportunity to take new skills from others and why not share yours with others.

### CODE REVIEW

**Comment by nairihar** [comment]
Hi @mcollina, Is there are any preconditions to join you?

**Comment by mcollina** [comment]
No, there are no preconditions to join! Welcome!

The README is conflicting.

**Comment by nairihar** [comment]
What is waiting for approval this pr?

**Comment by nairihar** [comment]
Thanks for your response @mcollina.
I have just fix the conflicts.

**Comment by wentout** [comment]
Welcome!

**Pull request merged**
