### PR TITLE
Revert "Add Separate Members Page"

### PR DESCRIPTION
**Pull request by wentout**
Reverts nodejs/package-maintenance#64

@mhdawson @mcollina @pertrai1 
I have to merge this, cause there are to much conflicts.
I'd better re-do everything again after. Sorry.

### CODE REVIEW

**Comment by pertrai1** [comment]
LGTM

**Comment by wentout** [comment]
@mhdawson I'm still working on it to land all in one. Please **do not merge** untill finish.

**Comment by wentout** [comment]
@pertrai1 @Emuentes @mhdawson @mcollina 

I think now it might happen as one.

**Comment by mhdawson** [comment]
Ok going to land as I think this moves us in the right direction and then we can check if we have captured all of the people.

**Comment by mhdawson** [comment]
I was thinking that we would just close the PR's for all of the people we now have covered in the README.md.  Any objections to that?

**Comment by wentout** [comment]
> I was thinking that we would just close the PR's for all of the people we now have covered in the README.md. Any objections to that?

All PRs were made from their [fork]/master to [package-maintenance]/master.
And, I shipped them to the revert branch. And made MEMBERS.md simultaneously.

Now, as they received contributor's, seems all PRs shipped to master.
But still I have to click all PRs merge buttons, cause this action still required.

And I hoped github will auto-merge them, as my branch was merged having commits of PRs.
But seems not, it doesn't work the same way as other git systems, it requires UI interaction.

So, the part with contribution worked good. And part with merging worked bit too complicated.
Though I still able to merge all accordingly to merged PRs.

**Comment by wentout** [comment]
So, yes, now I merged revert-64-members-page through command line interface, and yes, everything is there now. 

Merry Christmas mates. ;^)

**Pull request merged**
