### PR TITLE
doc: propose initial set of administrative members

### PR DESCRIPTION
**Pull request by mhdawson**
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>

### CODE REVIEW

**Comment by mhdawson** [comment]
First cut at my suggestion of the initial set of Administrative members based on 

* Requirements for administrative members in https://github.com/nodejs/package-maintenance#how-to-join
* Those I think have signed up/have been managing the pkgjs org and need access to continue doing that

**Comment by ljharb** [comment]
I'd like to be an administrative member as well.

**Comment by mhdawson** [comment]
@ljharb agreed should have added you to the initial list.

**Comment by dominykas** [comment]
Should @BethGriggs not be on this list?

**Comment by larson-carter** [comment]
How is this list selected? Can we document where people register/signup?

**Comment by mhdawson** [comment]
@larson-carter the requirements are here: https://github.com/nodejs/package-maintenance#how-to-join

Administrative members take on additional levels of responsibility with respect to managing the pkgjs organization and the other repositories managed by the working group. Administrative members should have a long standing involvement in the working group.

Individuals who have made significant contributions and who wish to be considered as an Administrative member may create an issue or contact an Administrative WG member directly. It is not necessary to wait for an Administrative WG member to nominate the individual.

This is an effort the boostrap with those who have 'a long standing involvement in the working group.', 'significant contributions' and have volunteered to `take on additional levels of responsibility with respect to managing the pkgjs organization`

**Comment by mhdawson** [comment]
@BethGriggs are are happy to help admin the pkgjs org? If so I'll add you.

**Comment by larson-carter** [comment]
@mhdawson sorry I wasn't completing my thought on the last comment. Could we add the  wg-membership link to this PR?

**Comment by BethGriggs** [comment]
@mhdawson sure, it would be useful to be able to add people to the relevant teams

**Comment by mhdawson** [comment]
@larson-carter added links to info on becoming an admin member.

@BethGriggs added you.

**Pull request merged**
