### PR TITLE
add basic wording for licensing and open the debate up to PRs.

### PR DESCRIPTION
**Pull request by ghinks**
# [Issue 160 licensing](https://github.com/nodejs/package-maintenance/issues/160)

In order to get the ball rolling with some actual prose. This may serve as a starting point. I'm not making any recommendations either for or against individual licenses. Rather I'm saying that we 
don't want
- restrictive
- patent

and do want
- the owner to have a license
- choose one appropriately 

I think it is not likely we actually would come across a project we want to support that has no license.

### CODE REVIEW

**Comment by ljharb** [comment]
Could we determine the most used licenses on npm (by querying the license field in package.jsons in all packages), and report those statistics here? That would serve as a recommendation without making anyone worried that we were giving legal advice.

**Comment by ghinks** [comment]
I think that is an excellent idea. Let me see what data the NPM folks have on that. I have an owed favor.

**Comment by ljharb** [comment]
@ghinks if they can provide it readily, awesome - otherwise we can use @ChALkeR’s tool to just look at al the public packages.

@Eomm excellent idea; it should be present and valid SPDX.

**Comment by dominykas** [comment]
Do we recommend/discourage using a LICENSE file?

**Comment by ljharb** [comment]
Recommend, alongside the SPDX field. Both are required.

**Comment by ghinks** [comment]
( in order of popularity )
- MIT
- Apache
- BSD
- ISC
- SEE LICENSE
- MPL
- [object Object]
- GPL
- CC0-1.0
- LGPL
- Unlicense
- pemrouz.mit-license.org
- Artistic-2.0
- WTFPL
- AGPL

1. The license is literally "SEE LICENSE", i.e. it refers to a license.txt
2. [object Object] is again literally the license field when people put JS in it
3. "Unlicense" is "The Unlicense", not un-licensed code
4. The WTFPL really is that popular

**Comment by ljharb** [comment]
to clarify; `[object Object]` is when they use the antiquated object form of the field, which still, however, can be normalized to a license - unfortunately they didn't seem to apply that normalization.

**Pull request merged**
