### PR TITLE
docs: promote all current drafts to top-level #373

### PR DESCRIPTION
**Pull request by zackschuster**
initial PR is very simple & can be iterated here as necessary.

### CODE REVIEW

**Comment by dominykas** [comment]
I think `docs/PUBLISH-BLOG.md ` had a different intent - were we going to publish it on the blog? In which case maybe it should stay in the drafts?

**Comment by zackschuster** [comment]
> I think `docs/PUBLISH-BLOG.md ` had a different intent - were we going to publish it on the blog? In which case maybe it should stay in the drafts?

assuming it's meant as a blog post, would it be good to have it in both spots? on the blog, and as promoted documentation?

**Comment by mhdawson** [comment]
@zackschuster in terms of the blog post having it stay in drafts does make sense to me.

**Comment by zackschuster** [comment]
done

**Review by dominykas — APPROVED** [review]

**Comment by mhdawson** [comment]
I think these two are just pretty much empty placeholders and should stay in draft

docs/drafts/code-of-conduct.md → docs/code-of-conduct.md
docs/drafts/repository-settings.md → docs/repository-settings.md

**Comment by zackschuster** [comment]
done

**Review by thescientist13 — APPROVED** [review]

**Review by lholmquist — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by Eomm — APPROVED** [review]

**Pull request merged**
