### PR TITLE
Fixsupport

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by mhdawson** [comment]
@nodejs/package-maintenance  I'd like to expedite this as people following the example will end up with incorrect support info.

**Review by AshCripps — COMMENTED** [review]
I think youve got an extra commit from this PR in here https://github.com/nodejs/package-maintenance/pull/424/files

**Review by rxmarbles — APPROVED** [review]

**Comment by mhdawson** [comment]
See I have an extra change I need to remove

**Comment by mhdawson** [comment]
@AshCripps fixed

**Review by styfle — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by ghinks — APPROVED** [review]

**Review by thescientist13 — APPROVED** [review]

**Review by BethGriggs — APPROVED** [review]

**Comment by BethGriggs** [comment]
+1 to expedite/fast-tracking this one

**Review by AshCripps — APPROVED** [review]

**Pull request merged**
